# Optimized Domain Scanner Configuration
# Based on comprehensive analysis findings

scoring:
  # Quality threshold maintained at 35 for 10K scaling
  approval_threshold: 35
  
  # Content scoring weights
  content_weight: 0.7
  ads_txt_bonus: 25
  premium_platform_bonus: 3
  b2b_relevance_weight: 0.25
  quality_indicator_bonus: 5

validation:
  # Network timeouts
  timeout_seconds: 15
  max_retries: 2
  dns_cache_ttl: 3600

discovery:
  # Quality targets based on 92.9% validation failure analysis
  target_validation_rate: 0.20  # 20% of discovered domains should be valid
  fallback_threshold: 0.10      # Switch to fallback if <10% valid
  
  # Keywords for B2B relevance scoring
  quality_keywords:
    - business
    - finance
    - technology
    - industry
    - professional
    - enterprise
    - news
    - media
    - marketing
    - investment

analysis:
  # Performance and monitoring settings
  track_performance: true
  detailed_logging: true
  export_borderline: true
  auto_threshold_suggestions: true

# Continuous Discovery Service Settings
continuous_discovery:
  target_total_domains: 10000         # TURBO MODE: Scale to 10K domains
  batch_size: 100                     # TURBO MODE: 5x larger batches
  delay_between_batches: 2            # TURBO MODE: Minimal delays
  max_runtime_hours: 24               # Safety limit - stop after this many hours
  progress_report_interval: 5         # Report progress every N batches
  auto_export_on_completion: true     # Export domains when target reached
  save_progress_every_batch: true     # Save progress after each batch

# TURBO MODE Performance Settings
turbo_mode:
  enabled: true
  concurrent_validation: 75           # 5x more concurrent domain checks
  llm_discovery_count: 150           # 5x more domains per LLM call
  validation_timeout: 5              # 3x faster validation timeout
  parallel_pipelines: 4             # Multiple discovery streams
  high_throughput_scoring: true     # Optimized scoring for speed
  
# Environment-specific overrides (optional)
environments:
  development:
    scoring:
      approval_threshold: 30  # More lenient for testing
    validation:
      timeout_seconds: 10
    continuous_discovery:
      delay_between_batches: 10  # Faster for testing
  
  production:
    scoring:
      approval_threshold: 35
    analysis:
      detailed_logging: false  # Reduce noise in production
    continuous_discovery:
      delay_between_batches: 60  # More conservative in production
